# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    dotnet tool update -g paket
    dotnet tool update fake-cli
  displayName: 'Install prereq'

- script: |
    dotnet test
  displayName: 'test'

- script: |
    fake build --target package
  displayName: 'test'
