# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    dotnet new tool-manifest
    dotnet tool update paket
    dotnet tool update fake-cli
  displayName: 'Install prereq'

- script: dotnet paket restore
  displayName: "Restore"

- script: |
    dotnet fake build --target test
  displayName: 'test'

- script: |
    dotnet fake build --target package
  displayName: 'package'

- script: |
    dotnet paket push --api-key $env:nugetkey $(ls *.nupkg)
  env:
    nugetkey: $(nugetkey)
  displayName: 'push'